### ISSUE TITLE
Add pkgbuild

### ISSUE THREAD

**Issue by kaikecarlos** [xDeltaFox/InfinityApp#2]
Adicionar PKGBUILD para os usuarios de arch oprimidos

**Comment by HajeSaft** [comment]
![image](https://user-images.githubusercontent.com/24378330/34329084-e2b390d2-e8d9-11e7-9642-d04f2d1879d0.png)
![image](https://user-images.githubusercontent.com/24378330/34329085-e2f6e756-e8d9-11e7-87df-1239843c4003.png)
![image](https://user-images.githubusercontent.com/24378330/34329086-e2f8c896-e8d9-11e7-8ef5-502114a6a033.png)
![image](https://user-images.githubusercontent.com/24378330/34329087-e318c380-e8d9-11e7-9b19-b5b752066add.png)
![image](https://user-images.githubusercontent.com/24378330/34329088-e31b9aba-e8d9-11e7-9c21-65cda2430444.png)
![image](https://user-images.githubusercontent.com/24378330/34329089-e32f5bd6-e8d9-11e7-802a-272993a4821d.png)
![image](https://user-images.githubusercontent.com/24378330/34329090-e3363bb8-e8d9-11e7-922c-92d60ea77b69.png)
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by xDeltaFox** [comment]
Seu comentário foi ouvido, e será criado uma versão do app para linux na próxima atualização que for vim lá pro final de janeiro ou começo de fevereiro.
